// Bluespace Shield Field Generator - defines

// Damage types for shields
#define BSHIELD_DAMTYPE_PHYSICAL 1
#define BSHIELD_DAMTYPE_EM 2
#define BSHIELD_DAMTYPE_HEAT 3

// Energy constants
#define BSHIELD_ENERGY_PER_HP 40000
#define BSHIELD_UPKEEP_PER_TILE 1000
#define BSHIELD_UPKEEP_IDLE 40
#define BSHIELD_SHUTDOWN_DISPERSION_RATE 10000000
#define BSHIELD_CHARGE_RATE 500000

// Breach thresholds (higher = less likely to breach at given integrity)
#define BSHIELD_MINOR_BREACH_THRESHOLD 99
#define BSHIELD_MAJOR_BREACH_THRESHOLD 50
#define BSHIELD_CRITICAL_BREACH_THRESHOLD 25

// Adaptive mitigation constants
#define BSHIELD_MITIGATION_MAX_BASE 50
#define BSHIELD_MITIGATION_MAX_RESEARCH 10
#define BSHIELD_MITIGATION_HIT_GAIN 5
#define BSHIELD_MITIGATION_HIT_LOSS 4
#define BSHIELD_MITIGATION_LOSS_PASSIVE 0.5

// Shield mode bitflags
#define BSHIELD_MODE_HYPERKINETIC (1<<0)
#define BSHIELD_MODE_PHOTONIC (1<<1)
#define BSHIELD_MODE_NONHUMANS (1<<2)
#define BSHIELD_MODE_HUMANOIDS (1<<3)
#define BSHIELD_MODE_SILICON (1<<4)
#define BSHIELD_MODE_ATMOSPHERIC (1<<5)
#define BSHIELD_MODE_BYPASS (1<<6)
#define BSHIELD_MODE_OVERCHARGE (1<<7)
#define BSHIELD_MODE_MODULATE (1<<8)
#define BSHIELD_MODE_EM (1<<9)
#define BSHIELD_MODE_DAMPEN (1<<10)

// Explosion dampening
#define BSHIELD_EXPLOSION_BLOCK 4

// Shield hit return codes
#define BSHIELD_ABSORBED 1
#define BSHIELD_BREACHED_MINOR 2
#define BSHIELD_BREACHED_MAJOR 3
#define BSHIELD_BREACHED_CRITICAL 4
#define BSHIELD_BREACHED_FAILURE 5

// Generator states
#define BSHIELD_OFF 0
#define BSHIELD_DISCHARGING 1
#define BSHIELD_RUNNING 2
#define BSHIELD_IDLE 3
#define BSHIELD_SPINNING_UP 4

// Generator repair stages (when broken) - 12 steps
#define BSHIELD_REPAIR_CROWBAR 0
#define BSHIELD_REPAIR_WELD_DEBRIS 1
#define BSHIELD_REPAIR_PLASTEEL 2
#define BSHIELD_REPAIR_WELD_CASING 3
#define BSHIELD_REPAIR_WRENCH_FRAME 4
#define BSHIELD_REPAIR_CABLES 5
#define BSHIELD_REPAIR_WIRECUTTER 6
#define BSHIELD_REPAIR_SCREWDRIVER 7
#define BSHIELD_REPAIR_URANIUM 8
#define BSHIELD_REPAIR_CRYSTAL 9
#define BSHIELD_REPAIR_MULTITOOL 10
#define BSHIELD_REPAIR_WELD_FINAL 11