#define SPELLTYPE_ABSTRACT "Abstract"
#define SPELLTYPE_SERVITUDE "Servitude"
#define SPELLTYPE_PRESERVATION "Preservation"
#define SPELLTYPE_STRUCTURES "Structures"

#define SIGIL_TRANSMISSION_RANGE 4

#define CLOCK_CULT_STARTING_COGS 8
#define TRAIT_STARGAZED "stargazed"
#define TRAIT_FASTER_SLAB_INVOKE "faster_slab_invoke"
#define STARGAZER_TRAIT "stargazer"
#define VANGUARD_TRAIT "vanguard"
#define MAXIMUM_COGSCARABS 6
#define SPECIES_GOLEM_CLOCKWORK "clockwork_golem"
#define COOLDOWN_MECHA_JUDICIAL_MARK "mecha_judicial_mark"
#define COOLDOWN_MECHA_STEAM_DISCHARGE "mecha_steam_discharge"

#define ANCHORING_CRYSTALS_TO_SUMMON 2
#define ANCHORING_CRYSTAL_CHARGE_DURATION 6 MINUTES
#define ANCHORING_CRYSTAL_COOLDOWN (ANCHORING_CRYSTAL_CHARGE_DURATION + 1 MINUTES)

#define ARK_STATE_BASE 0
#define ARK_STATE_CHARGING 1
#define ARK_STATE_ACTIVE 2
#define ARK_STATE_SUMMONING 3
#define ARK_STATE_FINAL 4

#define ARK_READY_PERIOD 5 MINUTES
#define ARK_ASSAULT_PERIOD 10 MINUTES
